Update to 7.10.0
EvidentSolutions/elasticsearch-analysis-voikko pull request #7
Opened 2020-11-29 11:18 UTC by mvh77

Update to work with ES 7.10.0. I'm no gradle expert, had to do what I had to do to make it work.

2020-11-30 09:19 UTC, komu requested changes
I can't merge this as it is, but I'd be happy to get this functionality in, if they come in sensibly layered commits that only do one logical thing in commit and come with comments and/or commit messages that motivate the changes.

So a plan would be something like:

1. Check that a clean build against `master` passes the tests on your environment. If not, what's the problem? Do you need better test data or do we need to fix the tests to reflect latest dictionary. If so, perhaps make a commit and PR to make the tests less dependent on the actual version of the dictionary.
2. Apparently everything else depends on upgrading Gradle? Let's do that first. Run `./gradlew wrapper --gradle-version 6.7.1` to upgrade Gradle. Check that tests pass. Commit the files modified by this task and open a PR for that.
3. Now check that if there are some further things that would help your life and work with both old and new version of ES. If there are, try to get them in to master as well. If not, just proceed to next step.
4. Make a minimal commit with changes needed to get from `7.3.2` to `7.1.0`. Comment things that are not obvious. Passing the `name` to `AbstractTokenizerFactory` is clear and obvious, excluding transitive dependencies is not.

2020-11-30 09:19 UTC, komu commented on .gitignore
> -gradle.properties
These shouldn't probably be in this PR. Gradle properties is ignored for a good reason and most of `.idea` is kept around for a good reason as well. 

Anyway, neither of these is in any way related to upgrading Elasticsearch.

2020-11-30 09:19 UTC, komu commented on build.gradle
> +// build with ex: ./gradlew clean build -Dvoikko.path=/usr/lib64 -Dvoikko.dict.path=/usr/lib/voikko/
`gradle.properties.example` already explains this.

2020-11-30 09:19 UTC, komu commented on build.gradle
> +version = '7.10.0'
Version of this plugin should not be the same as the version of Elasticsearch.

2020-11-30 09:19 UTC, komu commented on build.gradle
> +        exclude group: 'net.java.dev.jna', module: 'jna'
So this exclusion is because ES and Voikko use different versions of JNA, which are theoretically not compatible, but in practise they work together? This could probably do well with a comment explaining why this is necessary.

2020-11-30 09:19 UTC, komu commented on build.gradle
> +    name project.name
This should be left as it is.

2020-11-30 09:19 UTC, komu commented on build.gradle
> +forbiddenApisTest.enabled = false
This would probably want to be in the end of the build file with other similar things.

2020-11-30 09:19 UTC, komu commented on build.gradle
> -}
Did the new ES build system cause this to break somehow?

2020-11-30 09:19 UTC, komu commented on src/test/java/fi/evident/elasticsearch/voikko/analysis/VoikkoTokenFilterTests.java
> +                token("voikon", "voikko", 1),
It seems highly unlikely that upgrading Elasticsearch would change the results that Voikko produces. If you're getting different results, you're using a different dictionary with Voikko. If you are using the the latest full morpho dictionary, it could be reasonable to update the tests to use that, but that would be a different PR, unrelated to upgrading Elasticsearch.

(Actually it would probably be a good idea to not use the work 'voikko' in these tests, because its something that seems to break very easily depending on the dictionary used.)

2020-11-30 09:19 UTC, komu commented on src/main/java/fi/evident/elasticsearch/voikko/analysis/FinnishTokenizerFactory.java
>                                     @SuppressWarnings("unused") String name, // TODO do we need name somewhere?
You can remove `@SuppressWarnings("unused")` and the TODO now that this is actually used.

2020-12-01 07:30 UTC, mvh77 commented on src/test/java/fi/evident/elasticsearch/voikko/analysis/VoikkoTokenFilterTests.java
> +                token("voikon", "voikko", 1),
I'm running the tests with the dictionnary indicated in the README, but I have libvoikko 4.1.1, I suspect the difference could come from there. I suggest you check this on your side.

2020-12-01 07:34 UTC, mvh77 commented
Moro! I'm not going to be able to work on this any further. I have a copy of this building in a private repo and I'm submitting this to let you know the changes I've made. I don't know gradle and don't care to learn just for this.

2020-12-01 07:37 UTC, mvh77 commented on build.gradle
> -}
This complained about some mismatch, I didn't know how to fix it and it didn't seem necessary.

2020-12-01 07:45 UTC, komu commented
Yeah, sounds reasonable. Thanks for your contribution and research into this.

2020-12-01 07:45 UTC, closed without merging

2021-01-22 13:35 UTC, komu commented
@mvh77 We released a completely new plugin which has no dependency on Voikko and which should be easily portable to different versions of Elasticsearch: https://github.com/EvidentSolutions/elasticsearch-analysis-raudikko

It's drop-in replaceable with the old plugin, so I strongly recommend migrating to it. You'll get rid of all the management pain and can just install one plugin which works without further configuration.

I'll be archiving this repository, future development will happen on the other plugin.